language: java

jdk: openjdk8

after_success:
  - mvn clean coveralls:report

# addons:
#   sonarcloud:
#     organization: "stackroute"
#     token:
#       secure: "0.............="

# script:
#   - sonar-scanner
